# Generated by Django 2.2.6 on 2019-10-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(default='unknown', max_length=200)),
                ('location_gps_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('location_gps_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=200)),
                ('current_shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Shelter')),
            ],
        ),
    ]
