# Generated by Django 2.2.6 on 2019-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191108_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='profile_picture',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
