# Generated by Django 2.2.6 on 2019-11-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(default='unknown', max_length=200)),
                ('profile_picture', models.ImageField(default='images/default.png', upload_to='images/')),
                ('breed', models.CharField(default='unknown', max_length=200)),
                ('color', models.CharField(default='unknown', max_length=200)),
                ('age', models.IntegerField()),
                ('euth_date', models.DateField()),
                ('id_number', models.CharField(default='unknown', max_length=200)),
                ('current_pledges', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('neutered_spayed', models.BooleanField()),
                ('name', models.CharField(default='unknown', max_length=200)),
                ('description', models.TextField()),
                ('hw', models.BooleanField()),
                ('surrender_reason', models.CharField(default='unknown', max_length=200)),
                ('weight', models.IntegerField()),
                ('current_shelter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shelters.Shelter')),
            ],
        ),
    ]
