# Generated by Django 2.2.6 on 2019-11-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='current_shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.Shelter'),
        ),
    ]
