# Generated by Django 2.2.6 on 2019-11-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(default='unknown', max_length=200)),
                ('address', models.CharField(default='unknown', max_length=200)),
                ('phone', models.CharField(default='555-555-5555', max_length=200)),
                ('email', models.EmailField(default='example@email.com', max_length=100)),
                ('website', models.CharField(default='unknown', max_length=200)),
                ('primary_contact', models.CharField(default='unknown', max_length=200)),
            ],
        ),
    ]
